### ISSUE TITLE
Image not visible besides the form.

### ISSUE THREAD

**Issue by yasht01** [sagar-barapatre/Desi-Grill#1]
![image](https://user-images.githubusercontent.com/55907631/90511465-21f22b00-e17a-11ea-9ff9-497036495152.png)

**Comment by sagar-barapatre** [comment]
It's not image. It is basically a map displaying the location of the restaurant...It can be done by using the Google Maps API. If you could use it and get it done please go ahead.

**Comment by sagar-barapatre** [comment]
Also display map on the right side of the screen when clicked on the Sign Up button. There also map is required.

**Comment by yasht01** [comment]
Okay. I will work on this too.

**Comment by sagar-barapatre** [comment]
I resolved that issue. Thank you so much.
