### ISSUE TITLE
Visual scroll bar not working.

### ISSUE THREAD

**Issue by yasht01** [sagar-barapatre/Desi-Grill#4]
![Screenshot_20200819-142540.png](https://user-images.githubusercontent.com/55907631/90614207-ffb6e680-e227-11ea-9935-f49654adf1f5.png)
The visual scrollbar is stuck on the last dot.

**Comment by yasht01** [comment]
Hey @sagar-barapatre, can you point out the code for the visual scrollbar. I am not able to understand why the last dot is active after I explcitly mentioned not to.

**Comment by awknoman** [comment]
We can use any other type of scrollbar as the 'dot' scrollbar is not much useful. I may be wrong.

**Comment by yasht01** [comment]
Hey @sagar-barapatre please review my PR.
